name: Build Devrock Ant Tasks

on:
  workflow_dispatch:

jobs:
  run:
    uses: hiconic-os/hiconic.ci.workflows/.github/workflows/range.yaml@main
    secrets: inherit
    with:
      range: "[devrock-ant-tasks]"